# Autogenerated with SMOP 0.32-7-gcce8558
from smop.core import *
# 

    # process output of deterministic algorithm into data we need
    
    load('030117_234splhr_fixedtraining_testeps15_arrays.mat')
    qs=cell2mat(permute(trained_parameters(1,1,1,1,arange()),cat(5,arange(1,4))))
# pillonetto_bell/src/our_inputs/process_data.m:5
    q2s=qs[:,1]
# pillonetto_bell/src/our_inputs/process_data.m:7
    q1s=q1(arange(),2)
# pillonetto_bell/src/our_inputs/process_data.m:8
    q2_mu=mean(q2s)
# pillonetto_bell/src/our_inputs/process_data.m:10
    q2_std=std(q2s)
# pillonetto_bell/src/our_inputs/process_data.m:11
    q1_mu=mean(q1s)
# pillonetto_bell/src/our_inputs/process_data.m:12
    q1_std=std(q1s)
# pillonetto_bell/src/our_inputs/process_data.m:13
    # Also somehow process the error terms