# Autogenerated with SMOP 0.32-7-gcce8558
from smop.core import *
# 

    
@function
def evaluate_eivs(eivs=None,theta=None,*args,**kwargs):
    varargin = evaluate_eivs.varargin
    nargin = evaluate_eivs.nargin

    eivs=cell2mat(cellfun(lambda c=None: feval(c,theta),eivs,'UniformOutput',false))
# pillonetto_bell/src/evaluate_eivs.m:2
    return eivs
    
if __name__ == '__main__':
    pass
    