# Autogenerated with SMOP 0.32-7-gcce8558
from smop.core import *
# 

    K=size(thetas,2) - burnin
# pillonetto_bell/src/findP.m:1
    gamma=1.25
# pillonetto_bell/src/findP.m:2
    ths=thetas(arange(),arange(1,K))
# pillonetto_bell/src/findP.m:3
    P=6
# pillonetto_bell/src/findP.m:5
    Q=floor(dot(gamma,P)) + 1
# pillonetto_bell/src/findP.m:6
    a=amps_from_th(P,K,ths,y,rkhs_eigenfile,T,n,tau,data_path)
# pillonetto_bell/src/findP.m:8
    b=amps_from_th(Q,K,ths,y,rkhs_eigenfile,T,n,tau,data_path)
# pillonetto_bell/src/findP.m:9
    __,eifs=get_kernel_eigenstuff(300,T,rkhs_eigenfile,nargout=2)
# pillonetto_bell/src/findP.m:11
    fksCoarse=cell(P,1)
# pillonetto_bell/src/findP.m:12
    fksFine=cell(Q,1)
# pillonetto_bell/src/findP.m:13
    for i in arange(1,K).reshape(-1):
        fksCoarse[i]=f_from_a_eifs(a[:,i].T,eifs[1:P])
# pillonetto_bell/src/findP.m:16
        fksFine[i]=f_from_a_eifs(b[:,i].T,eifs[1:Q])
# pillonetto_bell/src/findP.m:17
    
    while logical_not(isPbigenough(fksCoarse,fksFine,T)):

        P=copy(Q)
# pillonetto_bell/src/findP.m:22
        a=copy(b)
# pillonetto_bell/src/findP.m:23
        fksCoarse=copy(fksFine)
# pillonetto_bell/src/findP.m:24
        Q=floor(dot(gamma,P)) + 1
# pillonetto_bell/src/findP.m:26
        b=amps_from_th(Q,K,ths,y,rkhs_eigenfile,T,n,tau,data_path)
# pillonetto_bell/src/findP.m:27
        for i in arange(1,K).reshape(-1):
            fksFine[i]=f_from_a_eifs(b[:,i].T,eifs[1:Q])
# pillonetto_bell/src/findP.m:29
        figure
        hold('on')
        coarseFcns=zeros(K,n)
# pillonetto_bell/src/findP.m:36
        for i in arange(1,K).reshape(-1):
            coarseFcns[i,:]=feval(fksCoarse[i],t)
# pillonetto_bell/src/findP.m:38
        plot(mean(coarseFcns,1),'b-')
        lo_up_mid=confidence_limits(fksCoarse)
# pillonetto_bell/src/findP.m:42
        loCo=lo_up_mid[1]
# pillonetto_bell/src/findP.m:43
        hiCo=lo_up_mid[2]
# pillonetto_bell/src/findP.m:44
        plot(loCo[t],'b--')
        plot(hiCo[t],'b--')
        fineFcns=zeros(K,n)
# pillonetto_bell/src/findP.m:50
        for i in arange(1,K).reshape(-1):
            fineFcns[i,:]=feval(fksFine[i],t)
# pillonetto_bell/src/findP.m:52
        plot(mean(fineFcns,1),'r-')
        lo_up_mid=confidence_limits(fksFine)
# pillonetto_bell/src/findP.m:55
        loFi=lo_up_mid[1]
# pillonetto_bell/src/findP.m:56
        hiFi=lo_up_mid[2]
# pillonetto_bell/src/findP.m:57
        plot(loFi[t],'r--')
        plot(hiFi[t],'r--')

    
    P