# Autogenerated with SMOP 0.32-7-gcce8558
from smop.core import *
# 

    
@function
def isPbigenough(fksCoarse=None,fksFine=None,T=None,*args,**kwargs):
    varargin = isPbigenough.varargin
    nargin = isPbigenough.nargin

    # fkCoarse (resp. fkFine)
    # is a K x n array where the k^th ROW is the sum of the first P (resp. Q=floor(gamma*P)+1)
    # eigenfunctions with coeffs a^k, where k is the #iteration of the MCMC
    
    
    e=0.02
# pillonetto_bell/src/isPbigenough.m:7
    #    gamma = 1.25;
    
    lumC=confidence_limits(fksCoarse)
# pillonetto_bell/src/isPbigenough.m:10
    lumF=confidence_limits(fksFine)
# pillonetto_bell/src/isPbigenough.m:11
    bool=condition(e,T,lumF,lumC,1) and condition(e,T,lumF,lumC,2) and condition(e,T,lumF,lumC,3)
# pillonetto_bell/src/isPbigenough.m:13
    return bool
    
if __name__ == '__main__':
    pass
    