# Autogenerated with SMOP 0.32-7-gcce8558
from smop.core import *
# 

    
@function
def Lmatrix(theta=None,P=None,T=None,rkhs_eigenfile=None,n=None,tau=None,*args,**kwargs):
    varargin = Lmatrix.varargin
    nargin = Lmatrix.nargin

    # OUTPUT:
    # P x n
    # 
    # Lmatrix(j,i) = L_i(theta,phi_j), starting everything at t=0.
    
    __,eifs=get_kernel_eigenstuff(P,T,rkhs_eigenfile,nargout=2)
# pillonetto_bell/src/Lmatrix.m:7
    Lmatrix=convolve_eifs(eifs,theta,P,n,tau)
# pillonetto_bell/src/Lmatrix.m:8
    return Lmatrix
    
if __name__ == '__main__':
    pass
    