# Autogenerated with SMOP 0.32-7-gcce8558
from smop.core import *
# 

    
@function
def sample_eigenfunctions(eifs=None,t=None,*args,**kwargs):
    varargin = sample_eigenfunctions.varargin
    nargin = sample_eigenfunctions.nargin

    # INPUTS:
    # eifs is a 1xP cell array of function handles containing the eigenfunctions of the RK
    # t is a vector of values to sample each eigenfunction with
    # 
    # OUTPUT:
    # sampled_eifs is n x P, each column is an ef
    P=length(eifs)
# pillonetto_bell/src/sample_eigenfunctions.m:8
    sampled_eifs=zeros(length(t),P)
# pillonetto_bell/src/sample_eigenfunctions.m:9
    for k in arange(1,P).reshape(-1):
        sampled_eifs[:,k]=feval(eifs[k],t)
# pillonetto_bell/src/sample_eigenfunctions.m:11
    
    return sampled_eifs
    
if __name__ == '__main__':
    pass
    