# Autogenerated with SMOP 0.32-7-gcce8558
from smop.core import *
# 

    
@function
def sample_parameter(th_km1=None,*args,**kwargs):
    varargin = sample_parameter.varargin
    nargin = sample_parameter.nargin

    alpha_vel=get_alpha_vel()
# pillonetto_bell/src/sample_parameter.m:2
    
    Vhat=Vhat()
# pillonetto_bell/src/sample_parameter.m:3
    thk=normrnd(th_km1,dot(alpha_vel,Vhat))
# pillonetto_bell/src/sample_parameter.m:4
    return thk
    
if __name__ == '__main__':
    pass
    