# Autogenerated with SMOP 0.32-7-gcce8558
from smop.core import *
# 

    P=15
# pillonetto_bell/src/test_1.m:1
    T=1
# pillonetto_bell/src/test_1.m:2
    tau=1 / 50
# pillonetto_bell/src/test_1.m:3
    n=50
# pillonetto_bell/src/test_1.m:4
    theta=matlabarray(cat(exp(1),10))
# pillonetto_bell/src/test_1.m:5
    t=arange(0,(T - tau),tau)
# pillonetto_bell/src/test_1.m:7
    assert_(length(t) == n)
    rkhs_eigenfile='green1_eigen'
# pillonetto_bell/src/test_1.m:10
    data_path='none'
# pillonetto_bell/src/test_1.m:11
    # generate i/o
    actual_u=pb_7p2_example_u()
# pillonetto_bell/src/test_1.m:14
    sampled_u=actual_u[t]
# pillonetto_bell/src/test_1.m:15
    # fprintf('Generating sample output y\n')
# y = zeros(1,n);
# y(1)=0;
# for i = 1:(n-1)
#     y(i+1) = L_i([5,9.22],actual_u,i,tau);
# end
    
    y=matlabarray(cat(0,7.88095366724e-05,0.0010312574002,0.00425802631203,0.0109487106743,0.0216727342166,0.0363299402797,0.0542128037926,0.0742872217889,0.0952438390518,0.115773735486,0.134695370185,0.151113977012,0.164215096458,0.173782968336,0.17950985025,0.181500188617,0.180170029832,0.176002392925,0.169616154122,0.16154778454,0.152696662331,0.143452966475,0.13461278297,0.126611577696,0.119861421106,0.11457859032,0.110958828817,0.108905374421,0.108205189637,0.108760246572,0.109861127152,0.111364541302,0.112570195812,0.112986485687,0.112348166642,0.110225955711,0.106496590351,0.101132319194,0.0942716224385,0.0861827407805,0.0773306326962,0.068069670897,0.0589579388906,0.0502928147264,0.0424323522744,0.035521972666,0.0295923564096,0.0246246942156,0.0204888398014))
# pillonetto_bell/src/test_1.m:25
    y_total=copy(y)
# pillonetto_bell/src/test_1.m:26
    # data_path = '030117_234splhr_fixedtraining_testeps15_arrays';
# 
# load(data_path,'y_total')
    
    eivs,eifs=get_kernel_eigenstuff(P,T,rkhs_eigenfile,nargout=2)
# pillonetto_bell/src/test_1.m:34
    sampled_eifs=sample_eigenfunctions(eifs,t)
# pillonetto_bell/src/test_1.m:35
    ce=convolve_eifs(eifs,theta,P,n,tau)
# pillonetto_bell/src/test_1.m:36
    Vy_th_=Vy_th(theta,P,T,n,tau,rkhs_eigenfile,data_path)
# pillonetto_bell/src/test_1.m:38
    Lmatrix_=Lmatrix(theta,P,T,rkhs_eigenfile,n,tau)
# pillonetto_bell/src/test_1.m:40
    dLmatrix_=dLmatrix(theta,P,n,Lmatrix_)
# pillonetto_bell/src/test_1.m:41
    d2Lmatrix_=d2Lmatrix(theta,P,n,Lmatrix_)
# pillonetto_bell/src/test_1.m:42
    dVy_th_=dVy_th(theta,P,T,n,eivs,Lmatrix_)
# pillonetto_bell/src/test_1.m:44
    d2Vy_th_=d2Vy_th(theta,P,T,n,eivs,Lmatrix_,dLmatrix_)
# pillonetto_bell/src/test_1.m:45
    d2logpy_th_=d2logpy_th(y,theta,tau,P,T,n,eivs,rkhs_eigenfile,data_path)
# pillonetto_bell/src/test_1.m:47
    Vh=Vhat(y,theta,tau,P,T,n,eivs,rkhs_eigenfile,data_path)
# pillonetto_bell/src/test_1.m:49
    # eigs(Vh)
# eigs(diag(diag(Vh)))