# Autogenerated with SMOP 0.32-7-gcce8558
from smop.core import *
# 

    
@function
def Vhat(y=None,thetaHat=None,tau=None,P=None,T=None,n=None,eivs=None,rkhs_eigenfile=None,data_path=None,*args,**kwargs):
    varargin = Vhat.varargin
    nargin = Vhat.nargin

    # This should compute an ordinary nTheta x nTheta array
    # represending the C-R lower bound for
    
    # y_total is the output signal
    
    
    d2logpy_th_=d2logpy_th(y,thetaHat,tau,P,T,n,eivs,rkhs_eigenfile,data_path)
# pillonetto_bell/src/Vhat.m:8
    d2logpth_=- infoTheta()
# pillonetto_bell/src/Vhat.m:10
    H=d2logpy_th_ + d2logpth_
# pillonetto_bell/src/Vhat.m:12
    Vhat=- inv(H)
# pillonetto_bell/src/Vhat.m:14
    return Vhat
    
if __name__ == '__main__':
    pass
    