# Autogenerated with SMOP 0.32-7-gcce8558
from smop.core import *
# 

    
@function
def d2eiv(theta=None,P=None,T=None,*args,**kwargs):
    varargin = d2eiv.varargin
    nargin = d2eiv.nargin

    # THIS IS FOR EXAMPLE 7.2 in PB
    
    # OUTPUT:
    # 3D matrix
    # P x nTheta x nTheta
    # Hessian of Lambda_j evaluated at theta, where the (j,s,r) entry is
    #       d^2 Lambda_j / dth_s dth_r
    
    nTheta=length(theta)
# pillonetto_bell/src/example72_inputs/d2eiv.m:10
    d2eiv=zeros(P,nTheta,nTheta)
# pillonetto_bell/src/example72_inputs/d2eiv.m:11
    return d2eiv
    
if __name__ == '__main__':
    pass
    