# Autogenerated with SMOP 0.32-7-gcce8558
from smop.core import *
# 

    
@function
def d2Vy_thu(theta=None,P=None,n=None,*args,**kwargs):
    varargin = d2Vy_thu.varargin
    nargin = d2Vy_thu.nargin

    # This is the derivative of the known covariance matrix
    # V(y|theta,u)
    # with respect to theta
    
    # FOR EXAMPLE 7.2 FROM PILLONETTO-BELL
    
    # The paper is not totally clear to me, but I think the v_i are iid Gaussian
    # with mean 0 and variance .05u(t) at time t
    
    # In other words, V(y|theta,u) does not depend on theta.
    
    nTheta=length(theta)
# pillonetto_bell/src/example72_inputs/d2Vy_thu.m:13
    d2Vy_thu=zeros(n,n,nTheta,nTheta)
# pillonetto_bell/src/example72_inputs/d2Vy_thu.m:14
    return d2Vy_thu
    
if __name__ == '__main__':
    pass
    