# Autogenerated with SMOP 0.32-7-gcce8558
from smop.core import *
# 

    
@function
def dLmatrix(theta=None,P=None,n=None,Lmatrix=None,*args,**kwargs):
    varargin = dLmatrix.varargin
    nargin = dLmatrix.nargin

    # OUTPUT:
    # P x n x nTheta, where dLmatrix(j,i,r) = dL_i(th,phi_j) / dth_r
    
    # EXAMPLE 7.2 FROM PILLONETTO-BELL
    
    nTheta=length(theta)
# pillonetto_bell/src/example72_inputs/dLmatrix.m:7
    dLmatrix=zeros(P,n,nTheta)
# pillonetto_bell/src/example72_inputs/dLmatrix.m:9
    dLmatrix[:,:,1]=Lmatrix / theta[1]
# pillonetto_bell/src/example72_inputs/dLmatrix.m:10
    dLmatrix[:,:,2]=dot(dot(- 2,theta[2]),Lmatrix)
# pillonetto_bell/src/example72_inputs/dLmatrix.m:11
    return dLmatrix
    
if __name__ == '__main__':
    pass
    