# Autogenerated with SMOP 0.32-7-gcce8558
from smop.core import *
# 

    
@function
def dVy_thu(theta=None,P=None,n=None,*args,**kwargs):
    varargin = dVy_thu.varargin
    nargin = dVy_thu.nargin

    # This is the derivative of the known covariance matrix
    # V(y|theta,u)
    # with respect to theta
    
    # FOR EXAMPLE 7.2 FROM PILLONETTO-BELL
    
    # The paper is not totally clear to me, but I think the v_i are iid Gaussian
    # with mean 0 and variance .05u(t) at time t
    
    # In other words, V(y|theta,u) does not depend on theta.
    
    # OUTPUT:
    # n x n x nTheta
    
    nTheta=length(theta)
# pillonetto_bell/src/example72_inputs/dVy_thu.m:16
    dVy_thu=zeros(n,n,nTheta)
# pillonetto_bell/src/example72_inputs/dVy_thu.m:17
    return dVy_thu
    
if __name__ == '__main__':
    pass
    