# Autogenerated with SMOP 0.32-7-gcce8558
from smop.core import *
# 

    
@function
def infoTheta(*args,**kwargs):
    varargin = infoTheta.varargin
    nargin = infoTheta.nargin
    
"""
    # Gives Fisher information matrix for p(theta), i.e. the prior on theta
    # OUTPUT:
    # nTheta x nTheta
    
    # For EXAMPLE 7.2 we assume that theta(1) and theta(2) are independent,
    # so the Fisher information matrix is diagonal.
    
    # theta(1)~exponential(1)? Jeffreys prior?
    # theta(2)~N(10,2)
"""
    
    infoTheta=matlabarray(cat([0,0],[0,0.25]))
# pillonetto_bell/src/example72_inputs/infoTheta.m:12
    return infoTheta
    
if __name__ == '__main__':
    pass
    
