# Autogenerated with SMOP 0.32-7-gcce8558
from smop.core import *
# 

    
@function
def pb_7p2_example_u(*args,**kwargs):
    varargin = pb_7p2_example_u.varargin
    nargin = pb_7p2_example_u.nargin

    input_=lambda s=None: dot(0.3,betapdf(s,12,7)) + dot(0.6,betapdf(s,4,11))
# pillonetto_bell/src/example72_inputs/pb_7p2_example_u.m:2
    input_=lambda s=None: feval(input_,s) + normrnd(0,dot(0.05,feval(input_,s)))
# pillonetto_bell/src/example72_inputs/pb_7p2_example_u.m:3
    return input_
    
if __name__ == '__main__':
    pass
    