# Autogenerated with SMOP 0.32-7-gcce8558
from smop.core import *
# 

    
@function
def Gk1(s=None,t=None,*args,**kwargs):
    varargin = Gk1.varargin
    nargin = Gk1.nargin

    Gk1=double(s > t)
# pillonetto_bell/src/rkhs/Gk1.m:2
    return Gk1
    
if __name__ == '__main__':
    pass
    