# Autogenerated with SMOP 0.32-7-gcce8558
from smop.core import *
# 

    
@function
def greenKernel2(T=None,*args,**kwargs):
    varargin = greenKernel2.varargin
    nargin = greenKernel2.nargin

    K2=lambda th=None,s=None,t=None: dot(th,(dot(dot(s,t),min(s,t)) - dot((s + t),min(s,t) ** 2) / 2 + (min(s,t)) ** 3))
# pillonetto_bell/src/rkhs/greenKernel2.m:2
    return K2
    
if __name__ == '__main__':
    pass
    