# Autogenerated with SMOP 0.32-7-gcce8558
from smop.core import *
# 

    
@function
def green1_eigen(j=None,T=None,*args,**kwargs):
    varargin = green1_eigen.varargin
    nargin = green1_eigen.nargin

    eiv=lambda th=None: dot(th[1],T ** 2) / (dot((j - 1),pi) + pi / 2) ** 2
# pillonetto_bell/src/rkhs/green1_eigen.m:2
    eif=lambda s=None: dot(sqrt(2 / T),sin(dot((s / T),(dot(j,pi) - pi / 2))))
# pillonetto_bell/src/rkhs/green1_eigen.m:3
    return eiv,eif
    
if __name__ == '__main__':
    pass
    