# Autogenerated with SMOP 0.32-7-gcce8558
from smop.core import *
# 

    
@function
def Kg1(th1=None,s=None,t=None,T=None,*args,**kwargs):
    varargin = Kg1.varargin
    nargin = Kg1.nargin

    Kg1=dot(th1,(T - max(s,t)))
# pillonetto_bell/src/rkhs/Kg1.m:2
    return Kg1
    
if __name__ == '__main__':
    pass
    